---
- hosts: "localhost"
  connection: "local"
  vars:
    users:
    - username: "dario.vemagi"
      groups: "adm,wheel,"
    - username: "gianluca.pellegrini"
      groups: "adm,wheel,systemd-journal"
  tasks:
  - name: "Creazione user account"
    user:
      name: "{{ item.username }}"
      groups: "{{ item.groups }}"
    with_items: "{{ users }}"
  - name: "Aggiunta deelle chiavi pubbliche"
    authorized_key:
      user: "{{ item.username }}"
      key: "{{ lookup('file', 'files/'+ item.username + '.key.pub') }}"
    with_items: "{{ users }}"
  - name: "Utenti sudo senza password"
    lineinfile:
      dest: "/etc/sudoers" 
      state: "present"
      regexp: "^%wheel"
      line: "%wheel ALL=(ALL) NOPASSWD: ALL"
